Указано имя наставника
htmlacademy-javascript/2073335-kekstagram-26 pull request #1
Opened 2022-06-01 09:08 UTC by Domish4

:)

2022-06-01 09:19 UTC, o-bender requested changes

2022-06-01 09:19 UTC, o-bender commented on Readme.md
> +* Наставник: `Павел Лукин`.
Добавь ещё ссылку на профиль:)
https://htmlacademy.ru/profile/id1313529

2022-06-02 09:36 UTC, o-bender requested changes

2022-06-02 09:36 UTC, o-bender commented on Readme.md
> +* Наставник: `Павел Лукин` (https://htmlacademy.ru/profile/id1313529).
Почти:)
Сейчас:
Студент: [Александра Левченко](https://up.htmlacademy.ru/javascript/26/user/2073335).
Наставник: `Павел Лукин` (https://htmlacademy.ru/profile/id1313529).

Должно быть:
Студент: [Александра Левченко](https://up.htmlacademy.ru/javascript/26/user/2073335).
Наставник: [Павел Лукин](https://htmlacademy.ru/profile/id1313529).
```
Студент: [Александра Левченко](https://up.htmlacademy.ru/javascript/26/user/2073335).
Наставник: `Павел Лукин` (https://htmlacademy.ru/profile/id1313529).
```
Осталось удалить кавычки и добавить квадратные скобки:)

2022-06-02 10:09 UTC, Domish4 commented on Readme.md
> +* Наставник: `Павел Лукин` (https://htmlacademy.ru/profile/id1313529).
А! Точно, почему-то не обратила на это внимание... надеюсь сейчас поправила

2022-06-02 10:37 UTC, merged