Добавлены вспомогательные функции
htmlacademy-javascript/2073335-kekstagram-26 pull request #2
Opened 2022-06-03 12:18 UTC by Domish4

2022-06-03 16:18 UTC, o-bender requested changes

2022-06-03 16:18 UTC, o-bender commented on js/main.js
> +const checkLineLength = (line, maxLength) => {
Всё хорошо и всё работать будет. Но тут надо пояснить:
### if
Воспринимай if как функцию вроде такой:
```
const if = (condition) => ...
```
Где condition это аргумент принимающий значения типа bool. Т.е. true или false.
Таким образом что бы ты не передавала в if оно преобразуется в bool. У JS есть свой собственное представление о том, что такое true, а что false. На пример 0 это false, а "0" это true. :)

### Операции сравнения
Операции сравнения это такие же функции, но выглядят чуть иначе. Просто что бы привычней было. И это функции возвращающие значения типа bool.

### Объединяем
Объединив всё вместе приходим к выводу что такую запись:
```
if (line.length <= maxLength) {
    return true;
}
return false;
```
Можно заменить на такую:
```
return line.length <= maxLength;
```

2022-06-06 05:42 UTC, Domish4 commented on js/main.js
> +const checkLineLength = (line, maxLength) => {
Очень полезно, спасибо! поправила :)

2022-06-06 05:54 UTC, Domish4 commented on js/main.js
> +const checkLineLength = (line, maxLength) => {
Я еще опустила ретурн и сделала так: (по тому как советуют в задании со стрелочными функциями)
`const checkLineLength = (line, maxLength) => line.length <= maxLength;`
Так же тоже можно?

2022-06-06 07:18 UTC, merged