Модуляция
htmlacademy-javascript/2073335-kekstagram-26 pull request #4
Opened 2022-06-24 14:00 UTC by Domish4

---
:mortar_board: [Модуляция](https://up.htmlacademy.ru/javascript/26/user/2073335/tasks/10)

:boom: https://htmlacademy-javascript.github.io/2073335-kekstagram-26/4/

2022-06-24 14:43 UTC, o-bender requested changes

2022-06-24 14:43 UTC, o-bender commented on js/util.js
> +checkLineLength(12, 13);
Этот вызов, да и сама функция checkLineLength, думаю, нам больше не нужна:) Она была для разогрева:)

2022-06-24 14:43 UTC, o-bender commented on js/data.js
> +const photos = () => Array.from({length: PEOPLE_COUNT}, (id, index) => createPhoto(index + 1));
Это функция, а функция должна в имени иметь глагол. Назови createPhotos

2022-06-24 14:43 UTC, o-bender commented on js/data.js
> +photos();
Вот этот вызов надо перенести в main.js. Запускать мы нашу программу будем в main.js.

2022-06-27 07:58 UTC, Domish4 commented on js/data.js
> +photos();
> Вот этот вызов надо перенести в main.js. Запускать мы нашу программу будем в main.js.

Все поправила!

2022-06-27 08:16 UTC, merged